{% set version = "2.1.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nomclust
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nomclust_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nomclust/nomclust_{{ version }}.tar.gz
  sha256: 2cc87f090168ad1817344f4521bb2df98a00f351344b6a7ba140c005ab131e00

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-cluster
    - r-dummies

  run:
    - r-base
    - r-cluster
    - r-dummies

test:
  commands:
    - $R -e "library('nomclust')"           # [not win]
    - "\"%R%\" -e \"library('nomclust')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=nomclust
  license: GPL (>= 2)
  summary: Package for hierarchical clustering of objects characterized by nominal variables.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - uday1889

# Package: nomclust
# Title: Hierarchical Nominal Clustering Package
# Authors@R: c(person("Zdenek", "Sulc", role = c("aut", "cre"), email = "zdenek.sulc@vse.cz"), person("Hana", "Rezankova", role = "aut", email = "hana.rezankova@vse.cz"))
# Author: Zdenek Sulc [aut, cre], Hana Rezankova [aut]
# Maintainer: Zdenek Sulc <zdenek.sulc@vse.cz>
# Version: 1.1.1106
# Date: 2017-6-6
# Description: Package for hierarchical clustering of objects characterized by nominal variables.
# Imports: cluster, dummies
# License: GPL (>= 2)
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-06-06 14:41:21 UTC; zdenek
# Repository: CRAN
# Date/Publication: 2017-06-06 14:51:41 UTC
