{% set version = "2.8.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nomclust
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nomclust_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nomclust/nomclust_{{ version }}.tar.gz
  sha256: fb4a6e550ec987937b2a6b6737e298ef742a02da4076d911a92d46e2d41789ae

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=0.11.0
    - r-clvalid
    - r-cluster
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.11.0
    - r-clvalid
    - r-cluster

test:
  commands:
    - $R -e "library('nomclust')"           # [not win]
    - "\"%R%\" -e \"library('nomclust')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=nomclust
  license: GPL-2.0-or-later
  summary: Similarity measures for hierarchical clustering of objects characterized by nominal
    (categorical) variables. Evaluation criteria for nominal data clustering.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - uday1889
