travis:
  secure:
    BINSTAR_TOKEN: AYRNn9QsPrni2qVXzS7DVzJTnjkvOULgDM2BKAVFdlpU3wJMEZulypQPzFrMB6Dqt0L/qWCkAiLs9kJgU2dRZRLmBwbUWDG9J0tQmPgouOiLldBAAtROqMMTZ1n5k0GaECy8MgiMbA3IH9DofRCu0zEpys7DISwa1rRTgA59CqXNiERP2I3FecLdVcFl/yehX8GQNtt+IS9qU4tGWFW3+X+5IJ8aPb4FxjXsWuK/xU4Afke9kks5Nq1CjXGe3WmeeKVAcNA6Wqa5aJlW9QIRAowYj+4qT5QVIftPiHO/Idln8mW5wP6Sr2VWJCOTTSeuJr/FLzXF7HfVyV4Aho2TfNSSYUP904moozU7Po/sni7yTAPPpHM2lheLVzJWinASXcuy1QlZsFo0FqMdNpnfj7FdBTf/6Za0+Bo2JGhi0EY+4RspF0EokiUqFshBIoXztx8smSmj2alMrwBtX4tXacjb5bK7phxHi80CgSR+S0GbEr3PUbsh3B0jr2T4rWoDMQXlUMTPsCM7UXayHBltxkPCn5W4xj1/HhKq6If2Ngd/glyirr6Cc5hRQXJtPy0Rka8CImJuBZvyzGJGlQuK9mL20K+lXjsEPq7R9dcmzhr2XGHP4gIttgrGJMJbJbMsWZCzWdc7omrFYY7/oxev4zzmhjxEpkqYv8uaWzpqsvI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
